language: node_js
node_js:
  - 'stable'
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
  -codecovgit 
  -codecov
  repo_token: h1Sdggigkfo9IuVs1aZPUI6P9zwc2vy1c
