language: node_js
node_js:
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c 'create database dhadh;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
after_success: npm run coverage
repo_token: h1Sdggigkfo9IuVs1aZPUI6P9zwc2vy1c
